### ISSUE TITLE
Naming and terminology review

### ISSUE THREAD

**Issue by alastairs** [waives/waives.net#84]
* [x] Ensure all `async` methods have an `Async` suffix (#91)
 * [x] Define overrides for all `async` methods accepting a `CancellationToken` (#92, #96, #97)
 * [x] Review error messages for clarity and correctness (#93)
 * [x] Ensure no ReSharper warnings or errors (#95)
 * [x] Ensure all public methods check for null/empty values (#94)
 * [x] Ensure names are consistent across the solution (#98)
